#Hyperparameters for OCNN + Terrain model

#Architecture Config
ocnn_lenet: True
spec_cnn: False
terrain_cnn: True
include_thermal: False

#Genral HPs
lr: 0.00014127166641043006
batch_size: 32
dropout_final: 0.3

#Terrain CNN
terrain_cnn_activation_fn: "leaky_relu"
terrain_cnn_conv_kernel_size: 2
terrain_cnn_dilation_rate: 1
terrain_cnn_dropout: 0.5
terrain_cnn_n_layers: 1
terrain_cnn_n_neurons_1: 256
terrain_cnn_n_neurons_2: 512
terrain_cnn_neuron_mult: 1
terrain_cnn_pool_kernel_size: 2
terrain_cnn_pooling_type: "avg"
terrain_cnn_stride: 1
terrain_cnn_stride_1: 1